### ISSUE TITLE
Houmwurk?

### ISSUE THREAD

**Issue by VladimirGaristov** [elsys/po-homework-2015-2#1]
Ey bo0s, Y U NO gibe uz houmwurk?
Bo0s, pleaz! Gibe uz houmwurk so we kan skor poyntz!

**Comment by migglu** [comment]
![53219408-300x300](http://jenrulon.com/wp-content/uploads/2015/02/53219408-300x300.jpg)
Утре вечер се събираме, правим си молебена за учителство, и ви пускаме домашното :)

**Comment by Yellobelly** [comment]
Stfu
bo$$ fAgT
На 23.02.2016 г. 22:12 "Владо" notifications@github.com написа:

**Comment by migglu** [comment]
![20063059_zps47103f7e](http://i82.photobucket.com/albums/j242/oldcavedog/prime1/20063059_zps47103f7e.jpg)

**Comment by VladimirGaristov** [comment]
![tvoe-vyrazhenie-lica_37945509_orig_](https://cloud.githubusercontent.com/assets/14371062/13523420/0f0bc738-e1fe-11e5-9d6f-67a055b17eb0.jpeg)
