### ISSUE TITLE
Домашно 3, задача 1.

### ISSUE THREAD

**Issue by georgi-tinqin** [elsys/po-homework-2015-2#100]
Трябва да се провери дали  егн-то е валидно ли? И защо максималната дължина на стринга  да е 12 а не 10?

**Comment by hspasov** [comment]
> Трябва да се провери дали егн-то е валидно ли?

 Да.

> И защо максималната дължина на стринга да е 12 а не 10?

Май заради нулевия байт, ама ако ще трябва да сме точни тогава дължината ще трябва да е 11.. Това не е най-важното :smile:

**Comment by mitkodkn** [comment]
> И защо максималната дължина на стринга да е 12 а не 10?

Знае се, че ще се въвеждат максимум 12 символа от скрипта. Ако дължината е повече от 10, ЕГН-то няма да е валидно.

**Comment by migglu** [comment]
Интересно защо сме писали 12 за максимална дължина, най-вероятно просто не можем да броим, защото не бяхме чак толкова афк когато го мислехме това...

#offtopic
12 бройна система е доста по-яка от 10 - https://www.youtube.com/watch?v=U6xJfP7-HCc

**Comment by bankin** [comment]
Изи отговор - за да валидирате и дължината на въведеното нещо.
