### ISSUE TITLE
домашно 3 задача 1

### ISSUE THREAD

**Issue by PetarFilipov** [elsys/po-homework-2015-2#102]
Малко странен въпрос но защо когато въвеждам егенето - 6101047500 като инт и след това взимам остатъка с %10 ми изписва 4??

**Comment by nbankin** [comment]
Пробвахте ли да изведете числото което сте прочели, за да видите колко е всъщност?

**Comment by PetarFilipov** [comment]
изписва съвсем различно число !?!

**Comment by nbankin** [comment]
А каква е максималната стойност, която мога да съхраня в int променлива?

**Comment by PetarFilipov** [comment]
сложих unsigned long long int и пк не става, а прочетох, че това позволява до 2 на 64 - 1

**Comment by ghost** [comment]
И аз имам същия проблем с моята програма!

**Comment by bankin** [comment]
добре, напишете входното число което подавате и това, което получавате

**Comment by PetarFilipov** [comment]
въвеждам - 6101047500, а принтира - 1806080204

**Comment by bankin** [comment]
Можете ли да дадете частта от кога, която чете, дели и печата числото

**Comment by ghost** [comment]
scanf("%d",&enter);
   for(i=0;i<10;i++)
   {
       box[i] = enter%10;
       enter= enter/10;
       printf("%d\n", enter);
   }
 Въведено - 6101047500
Изход - 1806080204

**Comment by nbankin** [comment]
Можете ли да ми кажете, какъв "%какво" се използва за четене на unsigned long long int ?

**Comment by PetarFilipov** [comment]
%llu
ама пак не става ;(

**Comment by bmutafov** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/14894196/14113846/58277cf8-f5dd-11e5-806e-a2947957e6c9.png)

**Comment by PetarFilipov** [comment]
странно написах #include <limits.h>
printf("%llu",ULLONG_MAX); 
и изведе само 4 милиарда
а в нета пише че е 20-цифрено число?!?

**Comment by nbankin** [comment]
В момента четете числото и извеждате числото с "%d", което служи за int стойности. Въпреки, че променливата ви е от друг тип няма как да прочетете по-голяма стойност от максималната за int. Четете %llu и извеждайте с него и вижте дали работи.

**Comment by PetarFilipov** [comment]
пробвах вече и пак не става

**Comment by PetarFilipov** [comment]
пробвах вече и пак не става

**Comment by Atira12** [comment]
При мен работи , Благодаря много :)

**Comment by migglu** [comment]
Върху пи-то ULLONG_MAX е 18446744073709551615...
Въпреки това, опитайте да използвате масив от чарове

**Comment by migglu** [comment]
Само като допълнение, в тази табличка, към която е приложен стандарта, пише минималната големина https://en.wikipedia.org/wiki/C_data_types#Basic_types
