### ISSUE TITLE
Дали да използвам atoi функцията

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#103]
Здравейте,
Имам въпрос относно функцията atoi в С. В stackoverflow и другите форуми се пише ,че трябва да стоя далеч от това чудо,но за сега не виждам друг вариант. 
Та въпросът ми е ,мога ли да го използвам в първа задача.
Благодаря предварително.
Поздрави,
Филип Пепегов 10г клас ,№28

**Comment by migglu** [comment]
Здравейте,

Ето [тук](https://www.daniweb.com/programming/software-development/threads/465515/tribal-knowledge-atoi-is-evil) има добро обяснение защо atoi е зло и какво точно му е злото. Вариантите са два - да използвате собствена имплементация, или (ако сте дочели статийката вече ще знаете) да погледнете за strtol, което сякаш превъзмогва недостатъците на atoi :)

Поздрави,
Александър
