### ISSUE TITLE
Задача 1, домашно 3

### ISSUE THREAD

**Issue by lachaka** [elsys/po-homework-2015-2#104]
Имам въпрос относно задачата с ЕГН-то.
Ако пича е роден 02.05.2004, то ЕГН-то ще започва с 044502XXXX. Може да е роден 1904 а просто месеца да е грешен. От къде ще знаем дали е валидно ЕГН-то? Или нас не ни интересува дали е възможно да има такъв човек.

**Comment by hspasov** [comment]
> От къде ще знаем дали е валидно ЕГН-то? 

От контролната цифра
