### ISSUE TITLE
Грешка на бота при проверка?

### ISSUE THREAD

**Issue by bmutafov** [elsys/po-homework-2015-2#105]
На първата задача на tem results от hw3 първите 2 примера ми ги изкарва грешни, а при мене си бацат как трябва?

**Comment by nbankin** [comment]
Линк към решението/папката?

**Comment by bmutafov** [comment]
Забравих. https://github.com/elsys/po-homework/tree/master/B/03/03
http://prntscr.com/alldjq

**Comment by migglu** [comment]
На края на входа скрипта не слага нов ред (\n) , та проверката за strlen се проваля. Тествайте си програмата без да въвеждате нов ред, а като въведете EOF на края (ctrl + z на виндоус, ctrl+d два пъти на *никс) и би трябвало да видите проблема.
