### ISSUE TITLE
Питане за 3 дом 

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#109]
Искам да питам малко глупав въпрос за трето домашно когато казвате "стринг с максимална дължина 12"
може ли да го представим като int enter = 6101047500 примерно или трябва да е char[12];

**Comment by nbankin** [comment]
И чрез двата варианта можете да постигнете максимален резултат, разликата е в последсвтие как ще работите с данните си.

**Comment by ghost** [comment]
Благодаря много . Извинете но само да ви кажа - помолих мой приятели които имаха час с вас да ви кажат че съм болен(ангина ) и бих искал отсрочка защото не се чувствах достатъчно добре да пиша първите 3 дни .
