### ISSUE TITLE
Задача 2 vsmisal

### ISSUE THREAD

**Issue by Ivaza** [elsys/po-homework-2015-2#11]
Само за уточнение, понеже не ми стана много ясно, как трябва да работи vsmisal?
Програмата чете символ по символ и в момента, в който се въведе последната буква l от vsmisal, да се изведе резултата? Да не ми даде timeout бота по този начин?
Или все пак трябва да се натисне enter тоест да е дума по дума с fgets?

Условията са доста неточни за нещо, което ще се проверява с бот. : (

**Comment by migglu** [comment]
Четенето би трябвало да е дума по дума, не разчитайте, че на края на входа ще има нов ред.
Може да използвате scanf("%s", ... )
