### ISSUE TITLE
testcase 3 и 4

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#110]
Здравейте,
Мога ли само да питам ,какви проверки трябва да се направят още за testcase 3 и 4 ,защото непрекъснато гърмят при мен.
Или поне ако може жокер :).
Поздрави ,Филип Пепегов 10г клас, №28

**Comment by bankin** [comment]
Коя задача от кое домашно?

**Comment by philip5505** [comment]
Първа от трето,но вече изтече времето

**Comment by nbankin** [comment]
https://github.com/elsys/po-homework/blob/master/G/03/28/task1.c#L87 ако control_number има стойност 10 вместо първо да я направите да бъде 0 и после да сравнявате, вие правите проверката дали 10 == egn_digit_holder[9], което със сигурност няма да бъде вярно, защото egn_digit_holder[9] държи само една цифра, след което правитое control_number да бъде 0 и приключвате фунцията. Не съм гледал какви са тест 3 и 4 но това е възможна грешка. Оправете си я, за да си повишите точките \* 0.7

**Comment by philip5505** [comment]
ок,благодаря Ви. Извинете за късния отговор.
