### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by pigglu** [elsys/po-homework-2015-2#111]
Eto vijdate li - ako izpitwahte na list4e, nqma6e da stawat takiwa ne6ta

original:
https://github.com/elsys/po-homework/blob/master/A/03/27/task2.c

kopipasta:
https://github.com/elsys/po-homework/blob/master/V/03/26/task2.c
https://github.com/elsys/po-homework/blob/master/V/03/18/task2.c

Mii ne mi hareswa. Shte go kaja na roditelskata sreshta.

**Comment by nbankin** [comment]
Благодаря Ви, госпожо Нейкова!
