### ISSUE TITLE
Въпрос относно някои функции на eval

### ISSUE THREAD

**Issue by DanielVladimirov** [elsys/po-homework-2015-2#114]
Здравейте, искам да питам как трябва да работят някои от функциите на втора задача, трето домашно.

! Връща само едно или нула ли? Примерно (! 120 = 0) или (! 0 = 1)

Делението цяло число ли трябва да изкарва, или дробно? И ако трябва да е цяло, надолу ли го кастваме, или по човешките стандарти?

**Comment by DanielVladimirov** [comment]
относно делението, нека кажем че е като деление от тип int/int, не за друго, ама скриптът след малко минава :)

**Comment by bankin** [comment]
! връща само 1 или 0.
Делението е int/int и връща int резултата, както би действало в нормална C програма.
