### ISSUE TITLE
Проблем с второ домашно

### ISSUE THREAD

**Issue by IvoTod** [elsys/po-homework-2015-2#116]
Втората ми задача от домашно 02 беше премахната от съученик които си беше объркал папката но след това направи опит да я възстанови с ctrl + c ctrl + v ама забрави минусите на изтрити линии код в github. След това ги премахнах но не видях, че е забравил да копира и затварящата скоба на някоя функция и сега скрипта ми е дал 0 точки и даваше само един warning за long int които трябва да е int за raspberry pi. Сега съм го оправил и  ме интересува какво ще стане с тва домашно
commit history - [https://github.com/elsys/po-homework/commits/master/A/02/15/task2.c](https://github.com/elsys/po-homework/commits/master/A/02/15/task2.c)

**Comment by migglu** [comment]
Имате 25 точки, колкото сте имали преди "поправката". Дори и да оправите warning-а след срока можете да вземете 0.7 \* макс, което е <25, затова оставате с 25.
