### ISSUE TITLE
Грешка в testcase

### ISSUE THREAD

**Issue by hspasov** [elsys/po-homework-2015-2#120]
Почти съм сигурен, че има грешка в testcase 2, task1 от homework 04.

> Примерен вход:
> 978-0-330-25864-8
> 
> Изход:
> 1

Мисля, че изходът трябва да е 0, защото вярната чексума за този номер би трябвало да е 7.

**Comment by hspasov** [comment]
Също така

> На входа получавате стринг с дължина до 15 символа

Май трябва string-ът да е с по-голяма дължина, ако входът ще включва и тирета.

**Comment by DanielVladimirov** [comment]
бъди напълно сигурен, че има грешка :laughing:

**Comment by bankin** [comment]
Вярно, стрингът ще бъде с дължина до 20 символа. Сега ще погледна и за валидността на дадения isbn.

**Comment by bankin** [comment]
Даденият isbn е напълно валиден, защо смятате, че не е верен?

**Comment by hspasov** [comment]
Заради чексумата:
http://www.isbn-check.de/checkisbn.pl?isbn=9780330258648&submit=test&lang=en
За да е верен, трябва да е:
http://www.isbn-check.de/checkisbn.pl?isbn=9780330258647&submit=test&lang=en

**Comment by migglu** [comment]
Правилно, и двете забележки са правилни.
Кой номер и от кой клас сте, за да ви дадем бонус точки :)

**Comment by hspasov** [comment]
№27, 10А
Благодаря!
