### ISSUE TITLE
Четвърто домашно

### ISSUE THREAD

**Issue by ivanganchev** [elsys/po-homework-2015-2#124]
Ще бъде ли възможно да бъде да бъде удължен срока на четвърто домашно поне до неделя включително, защото не само аз, но съм сигурен че и други хора няма да имат достъп до компютър поради пътувания и планове?

**Comment by georgi-tinqin** [comment]
И при мен е така.

**Comment by stilihristov** [comment]
^ Backing this up

**Comment by bankin** [comment]
Идеята ни беше в четвъртък да ви дадем друго домашно включващо уакзатели и структури, но ще помислим над това

**Comment by migglu** [comment]
На мен ми звучи ок, ще го обсъдим с останалите и ще пишем тук и в главното README.md

**Comment by stilihristov** [comment]
Господине,
  какво е крайното решение.Би било добре ако наистина го удължите  :)

**Comment by Stoyan-Ivanov** [comment]
^

**Comment by migglu** [comment]
Май всички сме за да го удължи ☺️

**Comment by martylery** [comment]
^

**Comment by martylery** [comment]
дали ще може да разберем дали сте го удължили и ако да - докога?

**Comment by bankin** [comment]
Check homepage
