### ISSUE TITLE
Домашно 4 Зад 1 

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#125]
Искам да питам как по- точно се изчислява чексумата . Прочетох линка и все пак не разбрах.

Благодаря предварително :)

**Comment by hspasov** [comment]
Чексумата е 13-тата цифра и тя се образува от първите 12 цифри. От тези 12 цифри първата (гледано от ляво на дясно) я умножаваш по 1, втората по 3, третата по 1, четвъртата по 3 и т.н. до 12-тата, която умножаваш по 3. Всичко това го събираш. Резултатът го делиш на десет и получаваш остатък. Този остатък го изваждаш от числото 10 и полученото ти е чексумата. Пример:
Имаме "978-1-55583-868-3"
Чексумата **3** се образува от "978-1-55583-868"
Следователно: 9**.1**+7**.3**+8**.1**+1**.3**+5**.1**+5**.3**+5**.1**+8**.3**+3**.1**+8**.3**+6**.1**+8**.3** =**147**
147 % 10 = **7**
Чексума: 10 - 7 = **3**

**Comment by ghost** [comment]
Благодарим много :+1:

**Comment by Atira12** [comment]
пример 978-0-330-25864
чексума = 8 
 получава се 103%10 = 3 
10 -3 != 8

**Comment by Atira12** [comment]
А това пример : 978-0-330-25864
Чексумата = 103 
103 %10 = 3 
10 - 3 != 8
