### ISSUE TITLE
Срок за предаване на домашно с изтекъл срок

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#126]
Здравейте,
Срок за предаване на домашно с изтекъл срок и получаване на точките \* 0,7 важи една седмица след като то е изтекло? Тоест ако третото е изтекло на 31.03.2016 23:59 , имаме време то 7-ми ,да предадем каквото можем ,нали?
Ако съм се объркал ,се извинявам
Поздрави,
Филип Пепегов №28 ,10г клас

**Comment by migglu** [comment]
Мда, правилно.
За първото и второ домашно имаше изключение, че беше до 31-ви срок, заради разни удължения и неясноти по домашното, но за следващите домашни е така.

**Comment by philip5505** [comment]
Добре ,благодаря Ви и тук. :+1:
