### ISSUE TITLE
Въпрос на първа задача ,четвърто домашно.

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#127]
Здравейте,
Имам въпрос относно първа задача на четвърто домашно. "чексумата на номера да е вярна", това предполагам са примерите отдолу ?
И още един въпрос - стринговете ще се въвеждат с тиретата или просто като числа?
Благодаря предварително.
Поздрави,
Филип Пепегов №28 ,10г клас

**Comment by philip5505** [comment]
![screenshot from 2016-04-04 11-00-44](https://cloud.githubusercontent.com/assets/13074343/14241568/a0b51720-fa54-11e5-9dfe-826a10dbb10c.png)

мисля ,че това е решението

**Comment by migglu** [comment]
Привет,
Да, това е начинът за пресмятане на чексумата.
Стринговете ще се въвеждат с тиретата.
Поздрави,
Александър

**Comment by philip5505** [comment]
Благодаря Ви.
