### ISSUE TITLE
въпрос - задача 1 - четвърто дмоашно.

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#128]
Здравейте ,
Имам въпрос относно кода ми на задача 1 от четвърто домашно. Знам ,че е малко малоумно да питам за собствените си творения,но можете ли да ми кажете къде е грешката. 
Премаме ,че тиретата са -3 ,когато конвертирам IBSN-a в интеджер.
Внаги ми изписва ,че не съвпадат чексумите(последното число).  

![default](https://cloud.githubusercontent.com/assets/13074343/14253694/2e01e9ec-fa95-11e5-8a20-c441ba376759.png)

**Comment by philip5505** [comment]
printf-a е просто проверка, временно съм го намърдал там.

**Comment by hspasov** [comment]
Ти пишеш

> digit_result = parsed_isbn_number[position_counter] \* multiplayer;

ама накрая трябва да получиш някакъв сбор. Проблемът е, че никъде не събираш единия digit_result със следващия. Съветвам ви преди да пускате issue-та да пробвате да слагате printf-ове навсякъде и така да проследите как всичко се променя. Това е един вид дебъгване и така се откриват грешки.

Също така multiplayer е хубаво да го промениш на multiplier.

**Comment by philip5505** [comment]
добре,видях къде са ми грешките. Не са в функцията, в която съм мислил ,че са. А за правописните грешки си е друг въпрос. Благодаря все пак.

**Comment by philip5505** [comment]
не са във функцията\* :Д

**Comment by philip5505** [comment]
:+1:
