### ISSUE TITLE
Втора задача, четвърто домашно

### ISSUE THREAD

**Issue by DanielVladimirov** [elsys/po-homework-2015-2#132]
Искам да питам ще подавате ли като случай cycle_complete докато вратата е в състояние STOPPED_WHILE_*, защото от забележката не се разбира много и ако ще го подавате, как да го третираме? (Не ви се бъркам, но бих предложил в този случай програмата да игнорира реда - нищо не става. Защото и в реалния свят ако сме спрели вратата в някаква фаза, колкото и време да минава, нищо не се случва.)

**Comment by DanielVladimirov** [comment]
също, нали няма проблем да има нов ред накрая на изхода, защото миналия път като го махнах с "\b" не ми зачетохте задачата(безкрайно глупав повод ако тябва да бъдем честни) и да не стават пак такива гафове...

**Comment by nbankin** [comment]
Няма да подаваме cycle_complete ако вратата е в STOPPED_WHILE_\* състояние. Ще ви отговоря малко по-късно на втория въпрос

**Comment by DanielVladimirov** [comment]
Благодаря

**Comment by DanielVladimirov** [comment]
Реших да я отоворя наново, да не забравите въпроса ми. Между другото той не се отнася само до тази задача, а по принцип. Защото нерядко трябва да правим завъртяни условия и прочее, само за да няма един нов ред или спейс накрая, за да ни бъде зачетена задачата.

**Comment by migglu** [comment]
В момента скрипта реже whitespace символите (space, tab) преди първия и след последния   неуайтспейс символ за всеки ред от изхода на програмата ви. Използва се функцията [strip](https://docs.python.org/3.4/library/stdtypes.html#str.strip) за това.
Всички символи, които не са [whitespace](https://docs.python.org/3.4/library/string.html#string.whitespace),  не се махат от скрипта и се зачитат като изход от програмата.
