### ISSUE TITLE
Въпрос - задача 3 - четвърто домашно

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#133]
Здравейте,

(Забележка: Ако има повече от една комбинация да се подредят в низходящ ред, ако ги сравняваме като стрингове.)
Как да ги подредя в низходящ ред ако са стрингове? Гледам сбора от аски кодовете на всеки символ или има друг начин?

Поздрави,
Филип Пепегов №28 ,10г клас

**Comment by nbankin** [comment]
Направете сортиране по азбучен ред и ще са подредени в правилен ред.

**Comment by philip5505** [comment]
Дообре, ще го помъдря това.
И още един въпрос - скриптът тази седмица ще се пуска ли?

**Comment by DanielVladimirov** [comment]
Мисля, че strcmp ги подрежда както трябва. Моля да потвърдите, тъй като така ще го правя аз.

**Comment by iordanivanov** [comment]
bump

**Comment by migglu** [comment]
Да, strcmp прави лексикографско сравнение, което е това което имаме предвид. 
Да, ще пуснем скрипта, и ще удължи срока до неделя ☺️
