### ISSUE TITLE
Трета задача, четвърто домашно

### ISSUE THREAD

**Issue by DanielVladimirov** [elsys/po-homework-2015-2#134]
Здравейте, искам да питам за четвърта задача - първият елемент от подадения низ винаги ли е положителен? От примерите заключвам, че да, но искам да съм сигурен.

За този пример говоря:
Примерен вход:
23457
7

Изход:
2-3-4+5+7=7
2+3+4+5-7=7

Тук е изпуснат случаят:
-2+3+4-5+7=7

**Comment by DanielVladimirov** [comment]
bump

**Comment by migglu** [comment]
Да, винаги е с +
