### ISSUE TITLE
Късен въпрос задача 2 домашно 1 

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#14]
Искам да питам , защото в програмата си използвам long word[200] не ми работи на конзолата ,но работи на CodeBlocks. И за това съм задал char word[20000] дали така да го оставям или мога нещо друго да направя?

**Comment by migglu** [comment]
word звучи сякаш трябва да е дума, т.е. стринг, т.е. символен низ, т.е. масив от чар-ове. Няма нужда да правите масива по-голям, щом е зададена максимална големина на всяка дума.

**Comment by ghost** [comment]
Благодаря :)!

**Comment by Atira12** [comment]
Благодаря !
