### ISSUE TITLE
Execution took more than 1 seconds?

### ISSUE THREAD

**Issue by mitkodkn** [elsys/po-homework-2015-2#154]
Всички testcase-ове са фейлнали на моя Task 3 от четвъртото домашно:
[https://github.com/elsys/po-homework/tree/master/A/04/09](https://github.com/elsys/po-homework/tree/master/A/04/09)

Струва ми се, че проблемът не е в мен. Ето какво показва конзолата:
![proof](https://cloud.githubusercontent.com/assets/3275194/14542653/b6fef216-0298-11e6-8b9d-a25299949205.png)

_input_ файлът съдържа следното:

> 23457
> 7

**Comment by ivanganchev** [comment]
Отново го има и този проблем при мен. Но при 2ра задача.

**Comment by Ivaza** [comment]
Не само на 4, а сега и на домашно 3 ми дава същия проблем.
https://github.com/elsys/po-homework/tree/master/A/03/12
Execution took more than 1 seconds, а всъщност ми е доста под 1 sec.
![bbb77fde32672f3ec6f91ec42c50297e91b445d3671ce98fd0 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/14937972/14742392/aab8b61a-08a4-11e6-869e-30f1fcc6fb1f.png)

**Comment by migglu** [comment]
Ще го погледна когато имам свободно време, което напоследък нямам... :disappointed:
