### ISSUE TITLE
Грешка в проверката на домашни

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#155]
Мисля че има грешка , защото 2 задача за която не са ми дадвн и точки работи. Пробвах с примера на условието и работи.

**Comment by ghost** [comment]
https://github.com/elsys/po-homework/blob/master/G/04/03/task2.c

**Comment by ghost** [comment]
Въпроса се отнася за 4 домашно 2 задача

**Comment by ghost** [comment]
Vhod : 
button_clicked
cycle_complete
button_clicked
button_clicked
button_clicked
button_clicked
button_clicked
cycle_complete
Izhod:
Door:CLOSED
Door:OPENING
Door:OPEN
Door:CLOSING
Door:STOPPED_WHILE_CLOSING
Door:OPENING
Door:STOPPED_WHILE_OPENING
Door:CLOSING
Door:CLOSED

**Comment by IvoTod** [comment]
Има space след Door: при изхода

**Comment by mitkodkn** [comment]
Скриптът би трябвало да trim-ва изхода. Май space-a не е проблем.

**Comment by IvoTod** [comment]
Но пък казва че е fail-нал testcase 1 от където ме довежда до мисълта, че
най-вероятно не trim-ва зададения на скрипта изход с който да проверява или
някъде има някой друг символ който да fail-ва проверката

2016-04-15 23:29 GMT+03:00 Dimitar Nikolov <notifications@github.com>:

**Comment by Catishere** [comment]
Няма ли някой който да вземе да го направи по advanced тоя генади

**Comment by bankin** [comment]
Ако го направите вие приемаме пул рекуести, няма как да маха всички спейсове винаги.. не е много оптимално
