### ISSUE TITLE
Ново домашно

### ISSUE THREAD

**Issue by nikolaystanishev** [elsys/po-homework-2015-2#161]
Кога ще качите ново домашно?

**Comment by philip5505** [comment]
Ако искаш може да не питаш за домашни на връх на Велик ден.

**Comment by mitkodkn** [comment]
Ники, прави си мозъчните атаки и не се обаждай :D

**Comment by IvoTod** [comment]
666t

**Comment by bankin** [comment]
Не всички класове бяха взели динамична памет и бяха празници, затова сме ви го спестили :)
