### ISSUE TITLE
Няма го четвърто домашно

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#164]
Здравейте ,
На 4-то домашно всички папки за изтрити.

**Comment by philip5505** [comment]
и цялата история е изтрита. Пише ,че последното бърникане в папката е преди месец

**Comment by mitkodkn** [comment]
Ако някой нарочно го е направил, го признавам :D

**Comment by bankin** [comment]
Да, точно така. Някой е махнал домашното, новината, че срокът беше удължен, както и последната презентация (номер 8 за динамична памет) от репото. Който разполага с файловете е добре дошъл да ги възстанови :)

**Comment by migglu** [comment]
git push --force
![Git push](http://i.imgur.com/R7tEQPA.gif)
