### ISSUE TITLE
Въпрос относно условието на Задача 2 от домашното

### ISSUE THREAD

**Issue by hspasov** [elsys/po-homework-2015-2#2]
Как трябва да бъдат отделени думите една от друга на входа? Със EOF или със спейс? А ако е със спейс, то:
- примерно ако напишем "something smth vsmisal something" и сложим EOF програмата чете само "something smth vsmisal"?
- или ако напишем "something smth vsmisa" след това когато напишем "l" програмата веднага извежда резултат?
- или ако въведем "something smth" и сложим EOF програмата продължава да иска да се въведе нещо и така докато не въведем "vsmisal"?

**Comment by azlekov** [comment]
Думите се отделят със спейс.
За първия пример: 

> примерно ако напишем "something smth vsmisal something" и сложим EOF програмата чете само "something smth vsmisal"?

програмата трябва да прочете само `something smth vsmisal`, но не е нужно да слагаш EOF, защото по условие за край на четенето считаме думата vsmisal.

За втория пример:

> или ако напишем "something smth vsmisa" след това когато напишем "l" програмата веднага извежда резултат?

Да, ако няма разбира се whitespace преди това, в противен случай `l` ще се счита за нова дума.

> или ако въведем "something smth" и сложим EOF програмата продължава да иска да се въведе нещо и така докато не въведем "vsmisal"?

За третия пример, мисля, че се подразбира от предишните два.

**Comment by azlekov** [comment]
Малка задачка за теб @hristo99 - Следващият час в рамките на 2-3 минути да разкажеш за EOF. Ще си го запиша да те подсетим в часа.

**Comment by philip5505** [comment]
Има грешка в примера на първа задача. Аз получавам 16478 ,а е написано
16512.

**Comment by philip5505** [comment]
Ако грешката е моя се извинявам.

**Comment by hspasov** [comment]
@L3K0V Благодаря, стана ми ясно.

@philip5505  Няма грешка - при мен примерът на първа задача се получава както трябва. btw трябваше да отвориш ново issue.
