### ISSUE TITLE
Въпрос за 2-ра задача

### ISSUE THREAD

**Issue by hris11** [elsys/po-homework-2015-2#21]
Дали на втора задача трябва думите да се въведат на 1 ред тоест като 1 стринг или всяка дума в стринг?
Благодаря предварително

**Comment by migglu** [comment]
Би трябвало да работи и в двата случая. Ако ползвате scanf("%s", ... ) ще работи и в двата.

**Comment by migglu** [comment]
Тука сякаш отговорихме?
