### ISSUE TITLE
грешка в първа задача (пример)

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#3]
Здравейте, 
Мисля ,че има грешка в задача 1 ,примера.
Получавам 16748 ,а не 16512. 
Пресметнах го и с калкулатор и пак излиза толкова.
Ако грешката е моя се извинявам.
Поздрави,
Филип Пепегов № 28,10г

**Comment by philip5505** [comment]
16478*

**Comment by philip5505** [comment]
грешката е моя,щот съм невнимателен :).
Отговора на живота за това е 42 :D

**Comment by migglu** [comment]
Супер, ей такива проблеми най-много обичам :D
