### ISSUE TITLE
Git push error

### ISSUE THREAD

**Issue by somalieca** [elsys/po-homework-2015-2#38]
"To https://github.com/elsys/po-homework.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/elsys/po-homework.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."
**Не се оправя нито с  'git pull', нито с 'git fetch origin'.**

**Comment by migglu** [comment]
При git pull и веднага след това git push би трябвало да стане

**Comment by mitkodkn** [comment]
Снощи имаше проблем, защото много хора предаваха домашни по едно и също време.
