### ISSUE TITLE
въпрос относно задача №3

### ISSUE THREAD

**Issue by DanielVladimirov** [elsys/po-homework-2015-2#4]
Здравейте, бих искал да питам какво точно ще рече "както и поле за брой на срещанията". Нашата структура вече не съдържа ли такова поле? Как точно трябва да изглежда извеждането накрая? Само изкарваме четирите думи ли?

Ако беше сложен примерен вход и изход на задачата поне два от трите ми въпроса щяха да имат отговор, затова горещо ви моля да ни направите един пример, а не после да търчим по вас по коридорите и да ви питаме защо задачите ни не са приети. Предварително благодаря.

**Comment by DanielVladimirov** [comment]
Ще помоля съучениците ми да не затварят въпроса без да е получил отговор. Ако те нямат планове за лятото, аз имам. Благодаря.

**Comment by azlekov** [comment]
Добавих формат на изхода за задачата.
