### ISSUE TITLE
Въпрос - задача 2.

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#5]
Здравейте,
Трябва ли да се чете и думата vsmisal когато се въвежда стринг на втора задача (обработва се хеша и т.н.).
Благодаря.

**Comment by azlekov** [comment]
Трябва да се прочете, защото с тази дума настъпва края на четенето, но тя не попада в хеширането и не се брои като срещана.

**Comment by philip5505** [comment]
Ок ,благодаря.
