### ISSUE TITLE
Точки за домашното

### ISSUE THREAD

**Issue by philip5505** [elsys/po-homework-2015-2#50]
Здравейте, искам само да питам къде ще са точките от домашните. 
Ако някъде го има и не съм видял, се извинявам.

**Comment by hspasov** [comment]
Headquarters: https://docs.google.com/spreadsheets/d/1bj6Y8O1POXFm2LN03ut5ORoGL7C-1lcWnt0Ij9WPJ-s/edit
Линкът се намира [тук](https://github.com/elsys/po-homework) в README.md

**Comment by migglu** [comment]
Ще има репорт от скрипта тук, а точките ще са в headquarters както е писал @hristo99

**Comment by migglu** [comment]
Репортите вече са факт, точките ще ги нанесен скоро...
