### ISSUE TITLE
Въпрос по първия изход на трета задача от домашното

### ISSUE THREAD

**Issue by bmutafov** [elsys/po-homework-2015-2#51]
На 2рото домашно 3та задача първия пример изхода според мен е грешен, като трябва да се направят 5 скока: от **(1 до 3) от (3 до -2) от (-2 до 3) от (3 до -2) от (-2 до 0)**?
![untitled](https://cloud.githubusercontent.com/assets/14894196/13724311/11665844-e88a-11e5-8954-ff30715fac48.png)
изходът не трябва ли да е :

```
1
5
```

както е например в 3тия пример?:
![untitled1](https://cloud.githubusercontent.com/assets/14894196/13724322/5add1a3a-e88a-11e5-831e-6217acd2e09c.png)

paint skills :100:

**Comment by DanielVladimirov** [comment]
bump

**Comment by migglu** [comment]
Дам, +2 бонус точки към това домашно :)

**Comment by migglu** [comment]
Това е решено?
