### ISSUE TITLE
Проблем относно условието на Задача 2 от домашно 02

### ISSUE THREAD

**Issue by hspasov** [elsys/po-homework-2015-2#52]
Имаме ограничение "Използвайте функцията find". Проблемът е, че никъде в интернет не намирам как се ползва тази функция в C.

**Comment by hspasov** [comment]
Извинявам се, в условието има "да се дефинира функция char\* find(char *haystack, char needle)", т.е. самите ние пишем функцията...

**Comment by migglu** [comment]
:+1:
