### ISSUE TITLE
Въпрос по задача 2 от домашно 2

### ISSUE THREAD

**Issue by mihailhernandez** [elsys/po-homework-2015-2#53]
Масива започва ли с индекс 0 , тоест ако имаме "Hello World" и дадем Needle "H" , то трябва да върне 0 ?

**Comment by DanielVladimirov** [comment]
Масивът ти не започва от началото на RAM стика, (не съм сигурен дали има променлива, която може да заеме нулата), а ти връщаш пойнтер, който сочи към елемент от масива. В случая на първия елемент това пак няма да е нула, а началото на масива. Тоест ако масивът ти започва от 0xfe356a, и функцията ти трябва да върне първия елемент, тя ще върне 0xfe356a, ако трябва да върне, че е нямало нищо, ще върне 0.

Надявам се не спойлнах твърде много :D

**Comment by migglu** [comment]
Да, както @DanielVladimirov казва, функцията ти трябва да връща адресът, а когато принтираш резултата индексите започват от 0
