### ISSUE TITLE
1во домашно

### ISSUE THREAD

**Issue by ivanganchev** [elsys/po-homework-2015-2#56]
Не знам тук ли е мястото да попитам обаче може ли да дадете някакво обяснение защо не сме получили точки на 1вото домашно. В моя случай на първа и трета задача?

**Comment by bankin** [comment]
https://github.com/elsys/po-homework/tree/master/A/01/13 - предполагам това е вашата папка? Както виждате има 1 тест кейс на 1ва задча, който не минава и 3та задача също. Имате време до четвъртък да си ги оправите и да качите нова версия на кода си.

**Comment by ivanganchev** [comment]
А задачите със скрипта ли се проверяват? И аз за това питам за подробности защото при мен работят а явно при вас не :/

**Comment by nbankin** [comment]
Да, скрипта вече работи. За 1ва задача - по-скоро бих заложил, че не си я тествал докрай. За 3та погледни имаше промяна в условието за сортирането на думите. Имаш време до четвъртък, както е написано [тук](https://github.com/elsys/po-homework) :)

**Comment by ivanganchev** [comment]
Благодаря :)
