### ISSUE TITLE
Task 03 Homework 01

### ISSUE THREAD

**Issue by stilihristov** [elsys/po-homework-2015-2#58]
Може ли да получа примерен вход и изход за task 03 от първото домашно?Добър отговор на въпроса ми ще е ако пратите линка към скрипта,за да може да си проверяваме домашните със скрипта преди Вас. Мерси :ocean: :ocean:

**Comment by bankin** [comment]
Тъпо исках да има повече от един assigned :/

Идеята е или да ви даваме входа и изхода по време на тестването през седмицата и да тестваме с други за "финално" оценяване след карйния срок или да не даваме входа и изхода и да се тества с едни и същи тестове през цялото време.

**Comment by stilihristov** [comment]
Ок,разбирам.А поне може ли да ми дадете някакъв примерен изход и вход,различен от този с който тествате,защото в момента задачата ми не е минала test case-овете и не съм сигурен какво точно би трябвало да изкарва.

**Comment by nbankin** [comment]
Изчакайте утрешното пускане на скрипта, ако и тогава има проблем, ще се опитам да ви помогна.

**Comment by migglu** [comment]
bump

**Comment by bankin** [comment]
Няма развитие
