### ISSUE TITLE
Въпрос за 3-та задача 2-ро домашно

### ISSUE THREAD

**Issue by IvoTod** [elsys/po-homework-2015-2#59]
Как точно трябва да handle-ва случая в който се въведат повече от 50 целочислени стойности преди EOF? С други думи дали ще дава проблеми ако спре да чете на 50-ия int?

**Comment by migglu** [comment]
Няма нужда да хендълвате този случай, това условие за 50-те числа е от ограниченията, няма да има тесткейс с повече от 50
