### ISSUE TITLE
Въпрос към задача 3 от домашно 1

### ISSUE THREAD

**Issue by mitkodkn** [elsys/po-homework-2015-2#6]
В условието на задача 3 се казва:

> Напишете програма, която чете думи докато не намери точно 4 думи с еднакъв хеш.

и

> Да се изведат думите с еднакъв хеш.

Това, което се вижда в изхода, обаче са няколко хеша и въведените възможности за думи с еднакъв хеш. Стигнало се е до четвърта дума с еднакъв хеш и след това са изпринтирани всички събрани хешове с всички четири въведени версии за думи с еднакъв хеш. Така ли е? Всмисъл, не става много ясно.

**Comment by stilihristov** [comment]
Ще помогне ако  качите примерен вход и изход.

**Comment by azlekov** [comment]
Изведеде хешове с повече от една дума, тоест колизиите. Описал съм как да изглежда изходът.

**Comment by migglu** [comment]
Може би трябва да са сортирани в нарастващ ред по хешът?

**Comment by mitkodkn** [comment]
А всмисъл така ли последно трябва да бъде?

**Comment by ivanganchev** [comment]
Според мен е малко тъпо да се казва такава информация в последния момент? Ако не са сортирани значи че няма да ни бъде приета задачата ли?

**Comment by DanielVladimirov** [comment]
Не че е нещо кой знае какво да се добави един сорт, може ли следващия път обявявянето му да бъде малко по-навреме? Добре че стана на въпрос в групата, че да обърна внимание, че условието на задачата е променено.

**Comment by migglu** [comment]
Всмисъл, ако не са сортирано в какъв ред сте го направили да ги извежда? Как скрипта ще трябва да го провери след това?
Когато се появи неяснота или двусмислие, както виждате, го отстраняваме в максимално кратък срок, но не можем да контролираме кога се появява. Ако ни попитате и го установим в деня на пускане на домашното ще бъде отстранено тогава, ако ни попитате 2 часа преди крайния срок - какво очаквате да се случи?
В крайна сметка можете да предавате и коригирате домашни и две седмици след крайния срок, но естествено ще получите по-малко точки.

**Comment by mitkodkn** [comment]
Скриптът освен че проверява изхода, прави и въвеждане. Допусках възможността хешовете да се принтират според реда на въвеждане на думите. Благодаря за уточнението!
