### ISSUE TITLE
Задача 2 

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#61]
Искам да питам в find трябва да return NULL ако не намерим нищо ,а става ли 0? Колкото знам е едно и също.

**Comment by bojan-dim** [comment]
Да, if( условие )return NULL; В условието пише, че трябва да е NULL, така че използвай NULL;

**Comment by migglu** [comment]
Ммм, не е точно едно и също, когато ползвате указатели е хубаво да използвате NULL
