### ISSUE TITLE
3та задача 1во 

### ISSUE THREAD

**Issue by ivanganchev** [elsys/po-homework-2015-2#62]
Имам въпрос свързан с test case-овете и условието на задачата. Може би аз не го схващам напълно, но output-a се разминава с какъвто трябва да бъде в условието. "Напишете програма, която чете думи докато не намери точно 4 думи с еднакъв хеш." - от това разбирам, че всичко въведено след четвъртата дума с еднакъв хеш не трябва да бъдe взетo впредвид.
input = "asd asd asd asd vzz xyz yzy zxz"
 output = "770 vzz xyz yzy zxz"
не трябва ли изхода да бъде
669 asd

**Comment by IvoTod** [comment]
Ако се повтаря дума не се брои, само се записва в списъка от unique hash-ове веднъж

**Comment by migglu** [comment]
Идеята е че се търсят точно колизии, а не еднакви думи.

**Comment by bankin** [comment]
Няма развитие
