### ISSUE TITLE
Въпрос относно отговор на първо домашно.

### ISSUE THREAD

**Issue by mstanimirov** [elsys/po-homework-2015-2#63]
Въпросът ми е възможно ли е от цял випуск само 2/3 теста да са верни - ако може да проверите случайно да няма някаква грешка при test case 3 - извинявам се ако няма.Също така ще е хубаво ако има как да видим вход и изход които се ползват или поне какъв изход очаква защото ми се е случвало да не ми зачете домашно за един-два спейса повече :D

**Comment by migglu** [comment]
Абсолютно е възможно, даже е факт :) Ако тесткейс 1 и 2 ви минават, а 3 не на тази задача, не е заради спейсове.
