### ISSUE TITLE
Въпрос за точките по домашно 1

### ISSUE THREAD

**Issue by ilianstoqdinov** [elsys/po-homework-2015-2#65]
Днес задача едно ми я изписваше като грешна когато я погледнах, а две работеше. Сега пише обратното едно работи а две не работи и пише, че не се компилира. Аз я проверих 2 задача с вашият пример и ми се получи. Има ли някакъв шанс да не работи правилно бота или се бъркам. Извинете ако е така.

**Comment by migglu** [comment]
Мммда, май сега като пуснах скрипта нещо се счупи :( Довечера ще го погледна, за сега вярвайте на предпоследното рънване на скрипта

**Comment by ilianstoqdinov** [comment]
Добре мерси
