### ISSUE TITLE
3та задача

### ISSUE THREAD

**Issue by ivanganchev** [elsys/po-homework-2015-2#8]
Въпрос по третата задача. Задължително ли е да ползваме поле към структурата occurance_t което да бъде масив от стрингове на думите и аз го направих без? {програмата ми не тръгваше с това поле}

**Comment by azlekov** [comment]
Силно препоръчително е!
Каква грешка ти даде точно? Как си дефинираш структурата? Как попълваш това поле-масив.

**Comment by ivanganchev** [comment]
Опитах се да напиша:
struct occurance_t
{
    int hash;
    int count;
    char words[4][200];
    int len;
};
Но ми дава segmentation fault.

**Comment by migglu** [comment]
Някъде пипаш извън този масив :)
