### ISSUE TITLE
Script error 

### ISSUE THREAD

**Issue by stilihristov** [elsys/po-homework-2015-2#81]
https://github.com/elsys/po-homework/tree/master/A/01/24
таск2.ц  според скрипта не извежда правилен изход,а при мен всичко е правилно.Моля обърнете внимание :ocean::ocean: スススス

**Comment by migglu** [comment]
По-скоро грешката да е при вас...

**Comment by stilihristov** [comment]
Оказа се,че да.Може ли да ръннете скрипта още 1 път да съм сигурен,че съм го оправил.Мерси

**Comment by stilihristov** [comment]
b
