### ISSUE TITLE
Домашно 02 задача 03

### ISSUE THREAD

**Issue by nikolaystanishev** [elsys/po-homework-2015-2#88]
Господине първо искам да ви попитам какво да правя като по погрешка съм качи задача 03 от първо домашно в папката за 02 домашо, а задача 03 от домашно 02 я имам в github като история на тази задача?
https://github.com/elsys/po-homework/commits/master/A/02/22/task3.c

И второ искам да ви попитам какъв е error-a на task2.c.
https://github.com/elsys/po-homework/blob/master/A/02/22/README.md

**Comment by mitkodkn** [comment]
За error-a: #89

**Comment by nikolaystanishev** [comment]
А за другото?
