### ISSUE TITLE
Относно проверката на домашно 02

### ISSUE THREAD

**Issue by IvoTod** [elsys/po-homework-2015-2#89]
https://github.com/elsys/po-homework/tree/master/A/02/15
Скриптът получава error при компилация но при мене го няма
![screenshot from 2016-03-18 12 03 04](https://cloud.githubusercontent.com/assets/10090727/13874591/94dd6534-ed01-11e5-9156-496268116b6d.png)
Откъде точно е грешката?

**Comment by migglu** [comment]
Грешката е

```
task2.c: In function â��mainâ��:
task2.c:15:3: warning: format â��%ldâ�� expects argument of type â��long intâ��, but argument 2 has type â��intâ�� [-Wformat=]
   printf("%ld", result - input);
```

или по-точно - когато изваждате два указателя вие очаквате да получите променлива от тип long, докато на машината на която се компилира се получава int. Това е задари разликите в архитектурите (компилираме и тестваме програмите върху raspberry pi 2).

Това би трябвало да ви изясни проблема :)
http://stackoverflow.com/questions/7954439/c-which-character-should-be-used-for-ptrdiff-t-in-printf

**Comment by mitkodkn** [comment]
@migglu Предлагам да сложите параметрите на машината, на която се компилират програмите, в README-то.

**Comment by IvoTod** [comment]
Не бяхте ли ни казвали в началото на годината, че трябва всички да си сложиме някакъв дистрибутор на линукс за да нямаме разминавания при компилиране? vsmisal сега и raspberry pi ли трябва да си слагаме?

**Comment by lachaka** [comment]
@IvoTod Raspberry pi e едноплатков компютър (микроконтролер), а не операционна система. Що се отнася самите ОС можеш да ги видиш тук -> https://www.raspberrypi.org/downloads/
Доста по-олекотени са в сравнение с нормалните линукс дистрибуции и затова при вас няма проблеми, а при бота има.

**Comment by hspasov** [comment]
Според мен не е справедливо да му се смята задачата за грешна, тъй като по никакъв начин не е могъл да знае, че има проблем. Това, че ползвате raspberry pi 2 защо не сте го споменали, щом има значение? Също така ми е любопитно защо ползвате raspberry pi 2 вместо компютър със архитектура, подобна на нашите компютри?

**Comment by migglu** [comment]
Вътрешно водим тежки дебати как да разрешим този проблем, вече почти сме ге измислили, вероятно четвъртък вечерта ще решим финално. За сега глобално валидното е, че ако домашното има warning, но въпреки това се компилира (и случайно работи), човек не би трябвало да бъде лишаван напълно от точки.

**Comment by migglu** [comment]
Тука май Банкин трябваше да отговори, но явно е забравил.
Последно го направихме така - когато домашно се компилира но има warnings, тестовете се изпълняват и за всеки минаващ тесткейс се взема по 1 точка. Т.е. ако задачата има 2 тесткейса и дава 14 точки, то ще вземете максимално 12. За първо и второ домашно това ще ви го опростим, т.е. ще получите максимален брой точки, въпреки че в репорта ще са по-малко.
