### ISSUE TITLE
Затваряне на issue

### ISSUE THREAD

**Issue by iordanivanov** [elsys/po-homework-2015-2#9]
как да затворя на някой issue-то за един преател питам

**Comment by iliancho99** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/8740515/13556697/10fd7770-e3e9-11e5-8012-fa6b96e84d98.jpg)

Ето така ако не става ползвай [това](https://www.google.bg/).

**Comment by DanielVladimirov** [comment]
Само пробвам как работи бутона

**Comment by mitkodkn** [comment]
Много яко

**Comment by ZacharyGeorgiev** [comment]
Изключителен бутон

**Comment by IvoTod** [comment]
bez da iskah go otvorih moe li help????!

**Comment by IvoTod** [comment]
opraih sa np

**Comment by iordanivanov** [comment]
kakvo

**Comment by iordanivanov** [comment]
O fak
pls zatvorete go ok ms

**Comment by iordanivanov** [comment]
mr. piggu give me strength

**Comment by iordanivanov** [comment]
Genady please fucking work for once will ya lad?

**Comment by iordanivanov** [comment]
fOK OFF

**Comment by mitkodkn** [comment]
improt

**Comment by iordanivanov** [comment]
deep dark issues
![rn_cn9da_400x400](https://cloud.githubusercontent.com/assets/15002638/13613117/5eae913a-e573-11e5-84f2-7df641aed3e1.jpg)

**Comment by migglu** [comment]
Колко туесари са нужни за да се затвори едно issue?

**Comment by IvoTod** [comment]
-15

**Comment by mitkodkn** [comment]
![12834826_1150524024987178_1470470063_n](https://cloud.githubusercontent.com/assets/3275194/13731585/822b4c10-e975-11e5-9e5c-4c98180ad259.jpg)

**Comment by mitkodkn** [comment]
-25
