### ISSUE TITLE
Относно втора задача на 2то домашно и втора задача на първо домашно

### ISSUE THREAD

**Issue by edyz69** [elsys/po-homework-2015-2#90]
На 15 или 16 не помня вече ми я бяхте приели 2 Задача от 2 домашно и ми бяхте дали 7 точки,после ми писахте,че има warningi,но при мене няма когато ми се компилира програмта ми компилира всичко точно.И за втора задача на първо домашно не мога да разбера warninga тъй като пак ми се компилира правилно,но по някакъв начин скрипта ми пише Execution took more than 1 seconds.

task2.c: In function â��mainâ��:
task2.c:17:4: warning: format â��%ldâ�� expects argument of type â��long intâ��, but argument 2 has type â��intâ�� [-Wformat=]
    printf("%ld",find(row,symbol)-row);
    ^

**Comment by nbankin** [comment]
Следи #89 за развитие.
