### ISSUE TITLE
Домашно 2 Питане! 

### ISSUE THREAD

**Issue by ghost** [elsys/po-homework-2015-2#92]
Искам да питам ,защото по-миналата седмица Г клас нямаше час с г-н Леков :
1.не сме имали упражнение на pointers(преди домашно 2  да е качено ) 
2. не ни е обяснено какво представлява в 3 задача EOF  (има хора-изключения ,които знаят какво е EOF , но са го научили от Softuni или други източници  ) .
Затова мисля че повечето от Г клас нямат нужните знания за задача 3 домашно 2.

**Comment by bankin** [comment]
EOF не е обяснявано през втория срок. Имаше го в няколко последователни домашни през първия срок и тогава беше обяснено за EOF и как се използва. Имаше дори EOF на едно от контролните през първия срок. Доста странно, че целият клас не знае за EOF.

Аргумента за упражнението за указатели е доста по-валиден.
