### ISSUE TITLE
Скрипта

### ISSUE THREAD

**Issue by georgi-tinqin** [elsys/po-homework-2015-2#93]
Преди да мине срока бях качил  task1 и task2, от второ домашно. Всичко беше наред след като бяхте пуснали скрипта и пишеше че имам 14/14 точки. Днес гледам, че  имам 7/14 точки и то само защото съм оставил неизползвана променлива, което не ми беше показано като еррор след като бяхте пуснали скрипта преди крайния срок. Бих искал да ми бъдат дадени точките обратно защото това не е моя грешка.

**Comment by migglu** [comment]
Линк към вашата папка?

**Comment by georgi-tinqin** [comment]
https://github.com/elsys/po-homework/tree/master/G/02/08 Георги Георгиев, номер 8, 10 г клас.
