### ISSUE TITLE
Без права ?

### ISSUE THREAD

**Issue by mihailhernandez** [elsys/po-homework-2015-2#94]
Изпратих си домашно 02 преди крайния срок и не мога да го merge-на , при което стана 12 : 00 и скрипта не ми е зачел задачата за предадена.

**Comment by bankin** [comment]
Защо се сетихте последния ден да проверявате дали имате права за домашото? Защо не помолихте някой човек от класа да ви приеме пул рекуеста навреме? Вече имате достъп.
