### ISSUE TITLE
домашно 1

### ISSUE THREAD

**Issue by ivanganchev** [elsys/po-homework-2015-2#97]
Извинете, но може ли да дадете малко повече подробности относно задачи които не са успяли да минат тест кейсовете, за да може да си ги оправим. Говоря за домашно 1.

**Comment by migglu** [comment]
Какво имате предвид под малко повече подробности?

**Comment by ivanganchev** [comment]
https://github.com/ivanganchev/po-homework-1/tree/master/A/01/13 тук само пише че съм fail-нал с минаването на тестовете, но не пише примерно какъв е бил моя изход и какъв всъщност трябва да бъде.Питам защото задачите при мен работят.

**Comment by migglu** [comment]
Мне, аутпута и очаквания нарочно не ги показваме :)
Погледнах ви кода на първата задата, на https://github.com/ivanganchev/po-homework-1/blob/master/A/01/13/task1.c#L25 не си инициализирате temp променливата, и от там най-вероятно получавате грешен хеш.
На третата на https://github.com/ivanganchev/po-homework-1/blob/master/A/01/13/task3.c#L20 не си инициализирате масивът, и най-вероятно имате глупости в началото му...

**Comment by migglu** [comment]
Ммм, не, на третата сякаш не е от там грешката, значи сигурно от някъде другаде идва
