### ISSUE TITLE
Оценка на домашно

### ISSUE THREAD

**Issue by EvgaDobreva** [elsys/po-homework-2015-2#99]
Г-н Чернаев,
поради проблем в моя компютър относно качването на домашните в github, изпратих домашните на следващия ден. Бихте ли ми казали кога ще бъдат проверени и какво ще бъде наказанието ми за закъснението от 16 часа.
Евга Добрева, 10 а клас, номер 10

**Comment by migglu** [comment]
Ще ги проверим като "поправени" до този четвъртък, и ще получите 0.7 от максималните точки.
